
import { notoSans } from './config/fonts';
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${notoSans.variable} antialiased`}
      >
        <Providers>
          <main className="mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
