import "./globals.css";
import { notoSans } from '../config/fonts';

import type { Metadata } from "next";
import { Providers } from "./providers";
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${notoSans.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <main className="mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
