import "./globals.css";
import { notoSans } from '../config/fonts';

import type { Metadata } from "next";
import {Providers} from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      className='dark'
      style={{colorScheme:"dark"}}
      >
      <body
        className={`${notoSans.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
