#!/bin/bash
# ============================================
# zona_raiz - Supabase Stack Startup Script
# ============================================
# This script:
#   1. Creates required Docker network
#   2. Generates JWT/keys if not present
#   3. Pulls Docker images
#   4. Starts the Supabase stack
#   5. Waits for Postgres
#   6. Runs database migrations
#
# Usage:
#   ./scripts/supabase-up.sh           # Start stack
#   ./scripts/supabase-up.sh status   # Check status
#   ./scripts/supabase-up.sh stop     # Stop stack
#   ./scripts/supabase-up.sh down    # Stop and remove
#   ./scripts/supabase-up.sh logs    # View logs
#   ./scripts/supabase-up.sh migrate # Run migrations
# ============================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.supabase"
ENV_EXAMPLE="$PROJECT_ROOT/.env.supabase"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi

    log_info "Prerequisites check passed"
}

# Load environment variables
load_env() {
    if [ ! -f "$ENV_FILE" ]; then
        log_warn ".env.supabase not found. Creating from template..."
        if [ -f "$ENV_EXAMPLE" ]; then
            cp "$ENV_EXAMPLE" "$ENV_FILE"
            log_warn "Please edit $ENV_FILE with your values before continuing."
            exit 1
        else
            log_error "No environment template found. Please create $ENV_FILE"
            exit 1
        fi
    fi

    # Load vars
    set -a
    source "$ENV_FILE"
    set +a

    log_info "Environment variables loaded"
}

# Generate keys
generate_keys() {
    local needs_generate=false

    # Check if keys need generation
    if [ -z "${GOTRUE_JWT_SECRET:-}" ] || [ "$GOTRUE_JWT_SECRET" == "your_jwt_secret_min_32_chars_generate" ]; then
        needs_generate=true
    fi

    if [ "$needs_generate" == "true" ]; then
        log_info "Generating JWT secret..."
        export GOTRUE_JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
        log_success "JWT secret generated"
    fi

    # Generate anon key if needed
    if [ -z "${SUPABASE_ANON_KEY:-}" ] || [[ "$SUPABASE_ANON_KEY" == eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRZD* ]]; then
        log_info "Generating anon key..."
        local anon_key=$(openssl rand -base64 32 | tr -d '\n')
        export SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.$anon_key"
        log_success "Anon key generated"
    fi

    # Generate service role key if needed
    if [ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ] || [[ "$SUPABASE_SERVICE_ROLE_KEY" == eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.E6IMV1iHfKh2i8N8N0t7tY5Y8t5t5t5t5t5t5t5t5t* ]]; then
        log_info "Generating service role key..."
        local service_key=$(openssl rand -base64 32 | tr -d '\n')
        export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.$service_key"
        log_success "Service role key generated"
    fi

    # Save to env file
    cat > "$ENV_FILE" <<EOF
# Generated by supabase-up.sh on $(date)
# DO NOT commit to version control!

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_DB=${POSTGRES_DB:-postgres}
POSTGRES_EXTERNAL_PORT=${POSTGRES_EXTERNAL_PORT:-5432}

GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
GOTRUE_JWT_EXP=${GOTRUE_JWT_EXP:-3600}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
GOTRUE_API_EXTERNAL_URL=${GOTRUE_API_EXTERNAL_URL:-http://localhost:8000}
SITE_URL=${SITE_URL:-http://localhost:3000}

KONG_HTTP_PORT=${KONG_HTTP_PORT:-8000}
KONG_HTTPS_PORT=${KONG_HTTPS_PORT:-8443}
KONG_ADMIN_PORT=${KONG_ADMIN_PORT:-8001}

NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}

SMTP_HOST=${SMTP_HOST:-mailhog}
SMTP_PORT=${SMTP_PORT:-1025}

PGADMIN_PORT=${PGADMIN_PORT:-5050}
PGADMIN_PASSWORD=${PGADMIN_PASSWORD:-admin}
DOMAIN=${DOMAIN:-localhost}

SUBNET=${SUBNET:-172.28.0.0/16}
EOF
    log_success "Keys saved to $ENV_FILE"
}

# Create Docker network
create_network() {
    log_info "Creating Docker network..."
    
    if docker network inspect supabase_network &> /dev/null; then
        log_info "Network already exists"
    else
        docker network create --subnet="${SUBNET:-172.28.0.0/16}" supabase_network
        log_success "Network created: supabase_network"
    fi
}

# Pull images
pull_images() {
    log_info "Pulling Docker images (this may take a while)..."
    
    docker pull supabase/postgres:17.1.0.147 || true
    docker pull kong:3.4-alpine || true
    docker pull supabase/gotrue:v2.158.1 || true
    docker pull supabase/postgrest:12.0.2 || true
    docker pull supabase/realtime:v2.30.23 || true
    docker pull supabase/storage-api:v1.11.7 || true
    docker pull supabase/meta:3.1.1 || true
    
    log_success "Images pulled"
}

# Start stack
start_stack() {
    log_info "Starting Supabase stack..."
    
    cd "$PROJECT_ROOT"
    
    docker-compose -f docker-compose.supabase.yml up -d --remove-orphans
    
    log_success "Stack started"
}

# Wait for Postgres
wait_for_postgres() {
    log_info "Waiting for PostgreSQL to be ready..."
    
    local max_attempts=60
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if docker exec supabase_postgres pg_isready -U "${POSTGRES_USER:-postgres}" &> /dev/null; then
            log_success "PostgreSQL is ready"
            return 0
        fi
        
        echo -n "."
        sleep 2
        attempt=$((attempt + 1))
    done
    
    log_error "PostgreSQL failed to start within ${max_attempts} attempts"
    return 1
}

# Run migrations
run_migrations() {
    log_info "Running database migrations..."
    
    # Check if migrations exist
    if [ ! -d "$PROJECT_ROOT/supabase/migrations" ]; then
        log_warn "No migrations found in supabase/migrations"
        return 0
    fi
    
    # Get list of migration files
    local migrations=($(ls -1 "$PROJECT_ROOT/supabase/migrations"/*.sql 2>/dev/null | sort))
    
    if [ ${#migrations[@]} -eq 0 ]; then
        log_info "No migrations to run"
        return 0
    fi
    
    log_info "Running ${#migrations[@]} migrations..."
    
    for migration in "${migrations[@]}"; do
        local filename=$(basename "$migration")
        log_info "  Running: $filename"
        
        docker exec -i supabase_postgres psql -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-postgres}" < "$migration" || {
            log_warn "  Migration $filename may have warnings (continuing)..."
        }
    done
    
    log_success "Migrations completed"
}

# Setup auth schema
setup_auth() {
    log_info "Setting up auth schema..."
    
    docker exec -i supabase_postgres psql -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-postgres}" <<'EOF' || true
-- Create auth schema if not exists
CREATE SCHEMA IF NOT EXISTS auth;

-- Create auth tables
CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    encrypted_password TEXT,
    email_confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    last_sign_in_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    confirmation_token TEXT,
    recovery_token TEXT,
    email_change_token_new TEXT,
    email_change_token_current TEXT,
    email_change INT,
    reauthentication_token TEXT,
    is_super_admin BOOLEAN DEFAULT false,
    factor_id TEXT,
    phone TEXT,
    phone_confirmed_at TIMESTAMPTZ,
    phone_change_token TEXT,
    phone_change INT,
    metadata JSONB DEFAULT '{}'::JSONB,
    aud TEXT,
    role TEXT,
    nonce TEXT,
    nonce_sent_at TIMESTAMPTZ,
    amr_claims JSONB DEFAULT '[]'::JSONB,
    webauthn_factors JSONB DEFAULT '[]'::JSONB,
    mfa_challenges JSONB DEFAULT '[]'::JSONB,
    mfa_factors JSONB DEFAULT '[]'::JSONB
);

CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    token TEXT UNIQUE NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    revoked BOOLEAN DEFAULT false,
    replaced_by_token TEXT,
    families TEXT,
    refresh_token_family_id TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON auth.users(email);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON auth.refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON auth.refresh_tokens(token);
EOF

    log_success "Auth schema setup complete"
}

# Show status
show_status() {
    echo ""
    echo "=========================================="
    echo "Supabase Stack Status"
    echo "=========================================="
    echo ""
    
    cd "$PROJECT_ROOT"
    docker-compose -f docker-compose.supabase.yml ps
    
    echo ""
    echo "=========================================="
    echo "Service URLs"
    echo "=========================================="
    echo " Kong (HTTP):      http://localhost:${KONG_HTTP_PORT:-8000}"
    echo " Kong (HTTPS):     https://localhost:${KONG_HTTPS_PORT:-8443}"
    echo " Kong Admin:       http://localhost:${KONG_ADMIN_PORT:-8001}"
    echo " PostgreSQL:       localhost:${POSTGRES_EXTERNAL_PORT:-5432}"
    echo " GoTrue:          http://localhost:9999"
    echo " PostgREST:       http://localhost:3000"
    echo " Realtime:        http://localhost:4000"
    echo " Storage:        http://localhost:5000"
    echo " Meta:           http://localhost:8080"
    
    if [ "${PGADMIN_PORT:-5050}" != "" ]; then
        echo " pgAdmin:         http://localhost:${PGADMIN_PORT:-5050}"
    fi
    
    echo ""
    echo "=========================================="
    echo "API Endpoints"
    echo "=========================================="
    echo " Auth:           http://localhost:${KONG_HTTP_PORT:-8000}/auth/v1"
    echo " REST:           http://localhost:${KONG_HTTP_PORT:-8000}/rest/v1"
    echo " Realtime:       ws://localhost:${KONG_HTTP_PORT:-8000}/realtime/v1"
    echo " Storage:        http://localhost:${KONG_HTTP_PORT:-8000}/storage/v1"
    echo ""
}

# Stop stack
stop_stack() {
    log_info "Stopping Supabase stack..."
    
    cd "$PROJECT_ROOT"
    docker-compose -f docker-compose.supabase.yml stop
    
    log_success "Stack stopped"
}

# Down stack
down_stack() {
    log_info "Removing Supabase stack..."
    
    cd "$PROJECT_ROOT"
    docker-compose -f docker-compose.supabase.yml down
    
    log_success "Stack removed"
}

# Show logs
show_logs() {
    cd "$PROJECT_ROOT"
    docker-compose -f docker-compose.supabase.yml logs -f "${1:-}"
}

# Main
main() {
    local command="${1:-start}"
    
    case "$command" in
        start)
            check_prerequisites
            load_env
            generate_keys
            create_network
            pull_images
            start_stack
            wait_for_postgres
            setup_auth
            run_migrations
            show_status
            log_success "Supabase stack is ready!"
            ;;
        status)
            show_status
            ;;
        stop)
            stop_stack
            ;;
        down)
            down_stack
            ;;
        logs)
            show_logs "${2:-}"
            ;;
        migrate)
            load_env
            run_migrations
            ;;
        restart)
            stop_stack
            sleep 5
            start_stack
            wait_for_postgres
            show_status
            ;;
        generate-keys)
            load_env
            generate_keys
            ;;
        *)
            echo "Usage: $0 {start|status|stop|down|logs|migrate|restart|generate-keys}"
            exit 1
            ;;
    esac
}

main "$@"